### ISSUE TITLE
Invisible Varia Suit, plus a softlock

### ISSUE THREAD

**Issue by Uiraya** [Dessyreqt/smrandomizer#6]
Seed 19830827 (this number has no significance, really), masochist

By absolute chance I managed to find an invisible Varia Suit. It was where a missile tank typically is after traveling through a long green pipe in the ceiling of Brinstar. Its sprite would stop me from rolling. After shooting it it revealed itself and I could collect it.

 (I got here by entering Brinstar from the tunnel on the way to the wrecked ship, as the Torizo gave me power bombs, and then just worked backwards, though I can't see any reason why one couldn't just proceed here normally.)

 Additionally, I found a way to softlock. In the large pink room in Brinstar (with the charge beam in the lower left hand corner) if you go to the left through an invisible door (directly under the missile tank near the grappling blocks) without power bombs in reserve you can become trapped. Once you super missile through the floor and drop down, you apparently need at least a bomb or you can't get out of this room.

 These randomizer mods are amazing, thanks so much :D

 edit: Just found an invisible power bomb (missile tank spot above charge beam). I'm pretty sure my emulator is old as shit (ZSNES 1.51) but I didn't encounter any kind of problem while playing LttP. 

 edit2: With 99 energy you can't shinespark out of the pit where you learn how to shinespark.

**Comment by Dessyreqt** [comment]
Invisible items are a part of the Speedrunner and Masochist seeds. This is because those difficulties feature fewer than normal items, so having some of them be invisible means you will have to check the items more thoroughly. There are a few places where invisible items will never spawn, but what you described is completely expected.

As for the softlock, this is unfortunately a thing that can happen, and short of changing the enemy, drop, or level design of the game, it won't be changeable. There are lots of little softlocks like this, and while it's certainly possible to fix them, it's very low on the priority list at the moment. Especially with a difficulty like Masochist, it's very important to be mindful of your ammo before you enter certain rooms.

Thanks for the feedback, and I hope you enjoy!
